"""Minimal FastAPI server for the dashboard and analyst chat."""

from __future__ import annotations

from pathlib import Path
from typing import Literal

from fastapi import FastAPI, HTTPException
from fastapi.responses import RedirectResponse
from fastapi.staticfiles import StaticFiles
from pydantic import BaseModel

from .analyst import AnalystError, answer_question, load_dashboard_data

REPO_ROOT = Path(__file__).resolve().parents[2]
FRONTEND_DIR = REPO_ROOT / "src" / "frontend"
OUTPUTS_DIR = REPO_ROOT / "outputs"
DASHBOARD_PATH = REPO_ROOT / "outputs" / "latest" / "dashboard_data.json"


class AnalystChatRequest(BaseModel):
    """Request body for analyst chat."""

    question: str
    provider: Literal["manual", "openai", "claude"] = "manual"


app = FastAPI(title="TikTok Content Agent", version="0.6.0")


@app.get("/api/health")
def health() -> dict[str, str]:
    """Return a lightweight readiness response."""
    return {"status": "ok"}


@app.get("/api/dashboard-data")
def dashboard_data() -> dict:
    """Return the latest dashboard JSON generated by the pipeline."""
    try:
        return load_dashboard_data(DASHBOARD_PATH)
    except AnalystError as exc:
        raise HTTPException(status_code=404, detail=str(exc)) from exc


@app.post("/api/analyst-chat")
def analyst_chat(request: AnalystChatRequest) -> dict:
    """Answer an analyst question from the latest dashboard data."""
    try:
        data = load_dashboard_data(DASHBOARD_PATH)
        return answer_question(request.question, data, provider=request.provider)
    except AnalystError as exc:
        raise HTTPException(status_code=400, detail=str(exc)) from exc


@app.get("/")
def root() -> RedirectResponse:
    """Open the static dashboard entrypoint."""
    return RedirectResponse(url="/index.html")

if OUTPUTS_DIR.exists():
    app.mount("/outputs", StaticFiles(directory=OUTPUTS_DIR), name="outputs")
app.mount("/", StaticFiles(directory=FRONTEND_DIR, html=True), name="frontend")


def main() -> None:
    """Run the local development server."""
    import uvicorn

    uvicorn.run("src.backend.server:app", host="127.0.0.1", port=8000, reload=False)


if __name__ == "__main__":
    main()
